### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zdkcxy** [LZ9/Hermes#1]
1.可以吧连接mmqt设置成全局模式的，只要连接一次
2.如果要断开某个订阅的话，最好弄个取消订阅的功能

**Comment by LZ9** [comment]
@zdkcxy 非常感谢你的建议
1、我的初衷是考虑到项目可以能有多个长连接的情况，所以我在HermesAgent.create()里去创建了HermesAgent对象，如果您的项目里只需要一条长连接，可以将HermesAgent在您的单例方法里创建（或者Service里创建）
2、一般来说调用disconnect()方法就可以断开长连接，即断开订阅。您指的是在不断开长连接的情况下取消订阅而不停止发送（即客户端只发送信息不接收数据）这样吗？

**Comment by zdkcxy** [comment]
是的，就是连接不断开，但是订阅的消息队列不能接收到数据

**Comment by zdkcxy** [comment]
通过通配符取订阅消息队列，服务1秒钟发送1000多条数据，在Android端不进行任何业务操作，只是接收，好像会出现ANR

**Comment by LZ9** [comment]
@zdkcxy 不好意思，最近比较忙还没来得及更新版本，MQTT这个主要还是基于paho.mqtt.android来封装，我看开源的这个工程也已经3-4年么得更新了。。。我自己常规使用是能走通推送业务，当时开发的时候只做了后台多手机端的并发测试，没有做单台手机的压力测试，可能确实会出现ANR，建议贴一下报错的日志，我根据日志找找源码，看下能不能找到问题。

**Comment by zdkcxy** [comment]
@LZ9 这个数据要等后台缓存一下，现在的话就只有1秒钟推送几十条数据

**Comment by zdkcxy** [comment]
@LZ9 现在数据我刚问了，现在不可以模拟一次性发送几万条数据

**Comment by zdkcxy** [comment]
@LZ9 这几天不好意思了，没登录github，在做其它的功能。。。

**Comment by LZ9** [comment]
已经添加静默开关【setSilent(isSilent: Boolean)】，设置为true时可以保持连接但不向外传递消息，默认false，使用 implementation 'cn.lodz:hermes:2.0.2'以上版本即可

**Comment by zdkcxy** [comment]
好的，谢谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lodz"<notifications@github.com&gt;; 
发送时间: 2020年5月28日(星期四) 下午5:00
收件人: "LZ9/Hermes";
抄送: "Mention";
主题: Re: [LZ9/Hermes] 建议 (#1)





 
已经添加静默开关【setSilent(isSilent: Boolean)】，设置为true时可以保持连接但不向外传递消息，默认false，使用 implementation 'cn.lodz:hermes:2.0.2'以上版本即可
 
&mdash;
