### ISSUE TITLE
似乎这个封装库没有使用username与password进行登录的功能？

### ISSUE THREAD

**Issue by JJERRYY** [LZ9/Hermes#2]
你好，这个封装库非常好用，但是一旦我需要username与password登录，似乎没有对应方法

**Comment by LZ9** [comment]
你好，如果是mqtt的username和password，在HermesAgent.create()的时候，可以调用setConnectOptions(options: MqttConnectOptions)方法，自定义一个MqttConnectOptions()对象，可以在这个对象里设置userName和password，例如：
options.userName = "XXXXX"
options.password = "XXXX".toCharArray()
