### ISSUE TITLE
建议：能否封装个取消订阅主题的函数

### ISSUE THREAD

**Issue by BatterMan-Li** [LZ9/Hermes#3]
我看到之前的问题，虽然能设置setSilent不接收消息，但是我的业务需求可以主动订阅和主动取消某一主题消息，但是disconnect是把可能订阅的一条长连接都关闭了吧！！！
而且mqtt本身自带取消订阅函数，能否封装下重新发布，否则我可能依赖你的源码修改使用了

**Comment by BatterMan-Li** [comment]
比如我连接一个Mqtt,然后动态订阅和退订，这个目前都不能实现，只有先设置订阅主体后再连接，不能连接后再订阅主体，退订主体

**Comment by LZ9** [comment]
我修改下，加一下动态订阅

**Comment by LZ9** [comment]
@BatterMan-Li 已新增动态订阅和退订方法，请使用implementation 'ink.lodz:hermes:2.1.2'版本
动态订阅调用setSubTopic()，动态退订调用unsubscribe()，退订监听器方法setOnUnsubscribeListener()，内部对订阅主题列表做了去重

**Comment by querli** [comment]
好的，谢谢！！！
